#!/usr/bin/env bash
export DEBUG_MODE=True
echo '===DEBUG MODE===='
echo $DEBUG_MODE
echo '================='
sudo /etc/init.d/redis-server stop
sudo /etc/init.d/redis-server start
python3 ../updateCache_thread.py &
python3 ../manage.py runserver 0.0.0.0:8000 --insecure
