#!/usr/bin/env bash
export DEBUG_MODE=True
echo '===DEBUG MODE===='
echo $DEBUG_MODE
echo '================='
./make-migrations-and-migrate
sudo service postgresql stop
sudo service postgresql start
cd .. && python3 manage.py test
cd script
python3 ../backup_thread.py &
python3 ../manage.py runserver 172.17.0.2:8000 --insecure
