#!/usr/bin/env bash
./make-migrations-and-migrate
sudo service postgresql stop
sudo service postgresql start
python3 ../manage.py collectstatic
python3 ../backup_thread.py &
python3 ../manage.py runserver 172.17.0.2:8000
# gunicorn -c ../gunicorn_config/config.py django_project.wsgi
