# Generated by Django 3.0.8 on 2020-09-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField(blank=True, default=None, null=True)),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'humidity',
            },
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'verbose_name_plural': 'temperature'},
        ),
    ]
