# Generated by Django 3.0.8 on 2020-09-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0002_auto_20200921_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpuTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpuTemperature', models.FloatField(blank=True, default=None, null=True)),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Cpu Temperature',
            },
        ),
    ]
