# Generated by Django 3.0.8 on 2020-09-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0005_growthrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthrate',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
