# Generated by Django 3.0.8 on 2020-10-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0007_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='verification',
            new_name='activation',
        ),
    ]
