# Generated by Django 3.0.8 on 2020-10-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0008_auto_20201029_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'AuthGroup',
            },
        ),
    ]
