# Generated by Django 3.0.8 on 2020-10-29 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0009_authgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='activation',
            new_name='activated',
        ),
        migrations.AddField(
            model_name='profile',
            name='permission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor_app.AuthGroup'),
        ),
    ]
