# Generated by Django 3.0.8 on 2020-10-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0010_auto_20201030_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('product', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'PlantData',
            },
        ),
    ]
