# Generated by Django 3.0.8 on 2020-10-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0011_plantdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantdata',
            old_name='price',
            new_name='growth_rate',
        ),
        migrations.RemoveField(
            model_name='plantdata',
            name='product',
        ),
        migrations.RemoveField(
            model_name='plantdata',
            name='time',
        ),
        migrations.AddField(
            model_name='plantdata',
            name='aruco_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='plantdata',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plantdata',
            name='seed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='plantdata',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plantdata',
            name='type',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
