# Generated by Django 3.0.8 on 2020-10-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0012_auto_20201030_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdata',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
