# Generated by Django 3.0.8 on 2020-11-08 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0014_auto_20201106_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('title', models.CharField(max_length=25)),
                ('log', models.CharField(max_length=100)),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor_app.AuthGroup')),
            ],
            options={
                'verbose_name_plural': 'MessageLog',
            },
        ),
    ]
