# Generated by Django 3.0.8 on 2020-11-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0016_auto_20201108_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagelog',
            old_name='group',
            new_name='user',
        ),
    ]
