# Generated by Django 3.0.8 on 2020-11-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0017_auto_20201108_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='type',
            field=models.CharField(default='', max_length=25),
        ),
    ]
