# Generated by Django 3.0.8 on 2020-11-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0018_messagelog_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'TaskStatus',
            },
        ),
    ]
