# Generated by Django 3.0.8 on 2020-11-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0019_taskstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CpuTemperature',
        ),
        migrations.DeleteModel(
            name='TimePrice',
        ),
    ]
