# Generated by Django 3.0.8 on 2021-01-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0020_auto_20201111_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=25)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'connections',
            },
        ),
    ]
